set(CMAKE_SYSTEM_NAME FreeBSD)
set(CMAKE_SYSTEM_VERSION 9)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_COMPILER clang-18)
set(CMAKE_CXX_COMPILER clang++-18)
set(CMAKE_C_COMPILER_TARGET x86_64-sie-ps5)
set(CMAKE_CXX_COMPILER_TARGET x86_64-sie-ps5)
set(CMAKE_AR llvm-ar-18)
set(CMAKE_RANLIB llvm-ranlib-18)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(sdk "$ENV{PS5_PAYLOAD_SDK}")
set(CMAKE_C_FLAGS_INIT "-isysroot ${sdk} -isystem ${sdk}/target/include -fno-stack-protector -fno-plt -femulated-tls")
set(CMAKE_CXX_FLAGS_INIT "-isystem ${sdk}/target/include/c++/v1 ${CMAKE_C_FLAGS_INIT}")
